gracefully handle browsers' autoplay + playback errors (in particular Safari/WebKit, which has the most aggressive autoplay restrictions)
```
NotAllowedError: The request is not allowed by the user agent or the platform in the
current context, possibly because the user denied permission.
```